#!/usr/bin/env bash

#use this script if your jhbuild sysdeps --install command is not working
#works awesome in fedora

dnf install -y \
libuuid-devel \
flac-devel \
speex-devel \
flex \
libtasn1-devel \
libffi-devel \
libXt-devel \
python3-cairo-devel \
libv4l-devel \
libexif-devel \
intltool \
cups-devel \
xorg-x11-drv-wacom-devel \
pam-devel \
libcap-devel \
libpng-devel \
exempi-devel \
libyaml-devel \
cairo-devel \
libxklavier-devel \
gmime-devel \
mesa-libGL-devel \
xorg-x11-xtrans-devel \
libpwquality-devel \
python3-devel \
cmake \
libXtst-devel \
llvm-devel \
rubypick \
hyphen-devel \
libpinyin-devel \
alsa-lib-devel \
libXdamage-devel \
libXrender-devel \
gperf \
libjpeg-turbo-devel \
fontconfig-devel \
libgcrypt-devel \
lcms2-devel \
anthy-devel \
mesa-libGLES-devel \
libXcomposite-devel \
libusbx-devel \
libtiff-devel \
startup-notification-devel \
libxslt-devel \
dbus-devel \
ragel \
libdmapsharing-devel \
libicu-devel \
libnice-devel \
xmlto \
libX11-devel \
libdvdread-devel \
libXext-devel \
libXi-devel \
sqlite-devel \
taglib-devel \
libatasmart-devel \
iso-codes-devel \
libhangul-devel \
libevdev-devel \
dbus-glib-devel \
xorg-x11-util-macros \
webkitgtk4-devel \
wireless-tools-devel \
libsmbclient-devel \
p11-kit-devel \
libvpx-devel \
libacl-devel \
libepoxy-devel \
libndp-devel \
avahi-gobject-devel \
libtool-ltdl-devel \
bluez-libs-devel \
libXinerama-devel \
mozjs24-devel \
readline-devel \
texinfo \
libXft-devel \
libdrm-devel \
ppp-devel \
libXrandr-devel \
nss-devel \
mpfr-devel \
libXfixes-devel \
wavpack-devel \
freetype-devel \
libproxy-devel \
libical-devel \
zlib-devel \
libxkbfile-devel \
libxcb-devel \
libSM-devel \
libcanberra-devel \
libarchive-devel \
python-devel \
poppler-glib-devel \
mesa-libwayland-egl-devel \
libgudev-devel \
libwebp-devel \
webkitgtk3-devel \
xorg-x11-proto-devel \
enchant-devel \
systemd-devel \
polkit-devel \
libnl3-devel \
json-c-devel \
libsndfile-devel \
libmusicbrainz5-devel \
bison \
libdb-devel \
mtdev-devel \
sbc-devel \
libxml2-devel \
gnutls-devel \
mesa-libgbm-devel \
plymouth-devel \
krb5-devel \
libgphoto2-devel \
xkeyboard-config-devel \
libXcursor-devel \
liboauth-devel \
ibgphoto2 \
gbm \
plymouth \
rdflib \
plymouth-devel \
libgphoto2-devel \
mesa-libgbm-devel

